name:                xdg-basedir-compliant
version:             1.2.0
github:              "kephas/xdg-basedir-compliant"
license:             BSD3
author:              "Pierre Thierry"
maintainer:          "pierre@nothos.net"
copyright:           "2022–2023 Pierre Thierry"

extra-source-files:
- README.md
- CHANGELOG

# Metadata used when publishing your package
synopsis:            XDG Basedir
category:            System
description:         See README.md

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- filepath
- path
- polysemy
- polysemy-plugin
- polysemy-zoo
- split

default-extensions:
- BlockArguments
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeOperators
# Polysemy still needs {-# LANGUAGE TemplateHaskell, DataKinds #-}

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fplugin=Polysemy.Plugin

tests:
  xdg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fplugin=Polysemy.Plugin
    dependencies:
    - xdg-basedir-compliant
    - aeson
    - hspec
    - QuickCheck
